---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: secureboot
spec:
  features:
    preferredSmm: {}
  firmware:
    preferredEfi:
      secureBoot: true
