---
name: Main
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          VERSION="${{ github.ref_name }}"
          for f in $(ls *bundle.yaml); do
            cp ${f} ${f/\.yaml/-${VERSION}\.yaml}
          done

          # Install yq and use it to update each resource with an instancetype.kubevirt.io/common-instancetypes-version annotation
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq && chmod +X ./yq
          for bundle in $(ls *bundle-${VERSION}.yaml); do
            yq -i '.metadata.labels.["instancetype.kubevirt.io/common-instancetypes-version"]=env(VERSION)' ${bundle}
          done
      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *bundle-${{ github.ref_name }}.yaml
            LICENSE
